# Generated by Django 3.1.7 on 2021-04-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SentiMate', '0004_auto_20210404_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
