# Generated by Django 3.1.7 on 2021-04-21 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SentiMate', '0012_testc1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestC1',
        ),
    ]
